name: 🔨 Build Test

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  build:
    name: Test Builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: go test ./...

      - name: Integration Tests
        run: bash run.sh
        working-directory: integration_tests/

      - name: Build
        run: go build .
        working-directory: cmd/httpx/
